-- AlterTable
ALTER TABLE "AiVisibilityReport"
ADD COLUMN IF NOT EXISTS "comparisonQueries" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "perceptionEvidence" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "competitorVisibility" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "aiResponseSamples" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "opportunities" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "recommendations" JSONB NOT NULL DEFAULT '[]';
